In [8]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

from pprint import pprint

import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pickle
import random

In [9]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [10]:
book = pd.read_csv('book.csv')
RUB = pd.read_csv('rub.csv')
user = pd.read_csv('user.csv')

In [25]:
book_list = list(book['Title'].unique())
book_list = sorted(book_list, key=str)
df_matrix = pd.DataFrame(columns = ['user'] + book_list)
df_matrix    #결과확인

Empty DataFrame
Columns: [user, #i세대 - 스마트폰을 손에 쥐고 자란 요즘 세대 이야기, &lt;자본&gt;에 대한 노트, (만화편) 2억 빚을 진 내게 우주님이 가르쳐준 운이 풀리는 말버릇, (사용자를) 생각하게 하지 마! - 웹과 모바일 사용성 원칙으로 디자인하는 UX, 0 영 ZERO 零 - 김사과 소설, 0-3세 아빠 육아가 아이 미래를 결정한다, 0.1밀리미터의 혁신 - 5년 안에 50배 성장한 발뮤다 디자인의 비밀, 0.1퍼센트의 차이 - 인종과 반인종의 교차로에서 제3의 길을 찾는 아주 특별한 DNA 이야기, 0~5세 말걸기 육아의 힘, 0~5세 애착 육아의 기적, 0년 - 현대의 탄생, 1945년의 세계사, 0순위 중드 표현 1200 - 이번엔 중국어다!, 0인칭의 자리, 0초 공부법 - 학교에서는 알려주지 않는, 시험을 지배하는 4가지 기술, 1% 유대인의 생각훈련 - 흔들리는 삶을 바로 세우는 5,000년 탈무드의 지혜, 1%만 바꿔도 인생이 달라진다, 1%의 카페를 찾아서 - 미국의 스페셜티 커피 CEO를 만나다, 1.4킬로그램의 우주, 뇌, 1.5도의 미래 - 기후변화, 우리가 알지 못하는 많은 이야기들, 100 인생 그림책 (리커버), 100% 스무 살 - 깜찍한 20대, 세상에 딴지를 걸다, 1001가지 해결중심 질문들, 1001개의 거짓말, 1002번째 밤 : 2010년대 서울의 미술들, 100℃ - 뜨거운 기억, 6월민주항쟁, 개정판, 100가지 물건으로 다시 쓰는 여성 세계사, 100년 동안 우리 마을은 어떻게 변했을까, 100년 전 우리는 - 개화에서 광복까지, 어린이를 위한 근대 역사 이야기, 100년 후에도 변하지 않는 부자 되는 지혜, 100단어 영어회화의 기적, 100달러로 세상에 뛰어들어라 - 금수저 없는 당신이 스스로 일자리를 만드는 법, 100만 번 산 고양이, 100명 중 98명이 틀리는 한글 맞춤법, 100배 주식 - 최고의 주식을 고르는 단 하나의 길, 100살 넘게 먹은 우리 학교, 100세 인생 - 저주가 아닌 선물, 100세 철학자의 인생, 희망 이야기 - 젊은 세대와 나누고 싶은, 100세 철학자의 철학, 사랑 이야기 - 젊은 세대와 나누고 싶은, 100초 정치사회 수업 - 지금 꼭 알아야 할 필수 지식 원포인트 레슨, 100편의 사랑 소네트, 101가지 비즈니스 모델 이야기 - 성공하는 스타트업을 위한, 2018 에디션, 1026, 10년 동안 적금밖에 모르던 39세 김 과장은 어떻게 1년 만에 부동산 천재가 됐을까? - 5년 만에 자산을 100배로 불린 투자고수 렘군의 단기속성 부동산 스쿨, 10년 후, 10년 후 부의 미래 - 시장을 뒤바꾸는 제4의 물결, 10년 후, 이곳은 제2의 강남이 된다 - 반드시 오를 곳을 찾아내는 부동산 투자 전략, 10대들을 위한 나의 문화유산답사기 1 - 신라 경주, 10대들의 토닥토닥 - 아무도 모르는 내 마음을 위한 힐링, 10대를 위한 생각하는 헌법, 10대를 위한 이븐 바투타 여행기, 10대를 위한 정의란 무엇인가 - 하버드대 마이클 샌델 교수의 정의 수업, 10대를 위한 행복한 독서토론 - 앵무새 죽이기부터 파우스트까지 인생책을 만나는 청소년 토론 길잡이, 10대에 운명을 개척하는 70가지 삶의 지혜, 10대와 통하는 과학 이야기 - 자연을 아는 만큼 삶이 성숙한다, 10대와 통하는 기독교 - 청소년과 예수의 커뮤니케이션, 10대와 통하는 동물 권리 이야기, 10대와 통하는 미디어 - 손석춘 선생님이 들려주는 나를 찾는 미디어 여행, 10대와 통하는 심리학 이야기, 10대와 통하는 음식 이야기 - 음식으로 바꾸는 세상, 10미터만 더 뛰어봐!, 10월유신과 국제정치, 10초 15분 1주일 - 일 잘하는 사람의 시간 관리법, 10퍼센트 인간 - 인간 마이크로바이옴 프로젝트로 보는 미생물의 과학, 11/22/63 - 1, 11/22/63 - 2, 11문자 살인사건, 11분, 127시간 - 전 세계를 감동시킨 아론 랠스톤의 위대한 생존 실화, 12가지 인생의 법칙 (반양장) - 혼돈의 해독제, 12가지 행복의 법칙 - 마음을 다루는 방식이 삶의 차이를 만든다, 12월 10일, 12월의 어느 날, 12주 실천 프로그램 - 집중, 헌신, 책무를 통한 목표 달성 실천 프로그램, 13.67, 13계단 - 제47회 에도가와 란포상 수상작, 13월에 만나요, 13의 저주, 13일의 김남우, 13층 나무 집, 140자 소설 - 세상에서 가장 짧고 기발한 99가지 특별한 이야기, 1417년, 근대의 탄생 - 르네상스와 한 책 사냥꾼 이야기, 145가지 궁금증으로 완성하는 모자이크 세계지도 - 한 권으로 끝내는 세계지리, 2020 전국지리교사모임 추천도서, 14살, 그때 꿈이 나를 움직였다 - 청소년을 위한 최정화 교수의 파워 멘토링, 14살에 처음 만나는 동양 철학자들 - 청소년을 위한 진짜 쉬운 동양 철학, 14세까지 공부하는 뇌를 만들어라 - 인지심리학자가 밝히는 뇌가 좋아하는 공부법, 15%의 이기는 사장 - 실패 확률 85%의 창업세계, 어떻게 살아남을 것인가, 150년 하버드 글쓰기 비법 (리커버) - SNS부터 보고서까지 이 공식 하나면 끝, 150년 하버드 글쓰기 비법 - SNS부터 보고서까지 이 공식 하나면 끝, 150억 부자의 부의 추월차선 - 아직 추월차선에 진입하지 못한 사람들을 위한 선물 같은 책, 1559년 라틴어 최종판 직역 : 기독교 강요 1~4 세트 - 전4권, 15소년 표류기, 15소년 표류기 (양장), 16세기 문화혁명, 17살, 나를 바꾼 한 권의 책 - 명문대생 39인이 말하는, 180도 - 관점을 뒤바꾸는 재기발랄 그림 에세이, 18년이나 다닌 회사를 그만두고 후회한 12가지, 18분 - 인생을 바꾸는 시간, 18세기 도시 - 교류의 시작과 장소의 역사, 18세기 조선 지식인의 발견 - 조선 후기 지식 패러다임의 변화와 문화 변동, ...]
Index: []

[0 rows x 19523 columns]

In [12]:
RUB.head()

id  Book_id  ... rate                          Title
0     510       81  ...  NaN                     푸른 오케스트라 1
1     186      135  ...  3.0                           구스 걸
2    9609      132  ...  4.0  구글의 미래 - 디지털 시대 너머 그들이 꿈꾸는 세계
3  340278      132  ...  0.0  구글의 미래 - 디지털 시대 너머 그들이 꿈꾸는 세계
4  121794      132  ...  NaN  구글의 미래 - 디지털 시대 너머 그들이 꿈꾸는 세계

[5 rows x 5 columns]

In [26]:
%%time

user_num = RUB['id'].unique()
book_num = len(RUB['Title'].unique())
book_list = np.array(book_list)
print(len(user_num))

user_score_list = []    # df_matrix에서 'user' 컬럼을 제외한 컬럼. 즉, title 컬럼
for num in user_num:
    user_score_list = [0 for i in range(book_num)]    # 값을 0으로 초기화
    df_tmp = RUB[RUB['id'] == num]    # 각 유저별로 묶는다
    for j in df_tmp.index:
        df_tmp = df_tmp.fillna(0)
        try:
            i = np.where(book_list==df_tmp.Title[j])[0][0]
            user_score_list[i] = df_tmp.loc[j]['rate']
        except:
            continue
        df_matrix.loc[num] = [num] + user_score_list    # 행채우기

350
CPU times: user 11min 44s, sys: 240 ms, total: 11min 44s
Wall time: 11min 45s


In [28]:
df_matrix = df_matrix.reset_index()
print(df_matrix)

     index  ...  힘의 역전 - Turn the Power Around
0        0  ...                            0.0
1        1  ...                            0.0
2        2  ...                            0.0
3        3  ...                            0.0
4        4  ...                            0.0
..     ...  ...                            ...
345    345  ...                            0.0
346    346  ...                            0.0
347    347  ...                            0.0
348    348  ...                            0.0
349    349  ...                            0.0

[350 rows x 19524 columns]


In [29]:
# 유틸리티행렬 pickle 저장
file = df_matrix
directory = open('utilitymatrix', 'wb')
pickle.dump(file, directory)
directory.close()

In [30]:
user_name = list(df_matrix['user'].unique())
#user_name = sorted(user_name, key = str)
user_name = pd.DataFrame(user_name)
user_name.columns = ['user_name']

# user_name pickle 저장
file_user = user_name
directory_user = open('user_name', 'wb')
pickle.dump(file_user, directory_user)
directory_user.close()

In [31]:
# pickle로 저장한 user_name data frame open
f = open('user_name', 'rb')
user_name = pickle.load(f)
user_name = user_name

In [32]:
# pickle로 저장한 유틸리티 행렬 DATA LOAD
f = open('utilitymatrix', 'rb')
utilitymatrix = pickle.load(f)

df = utilitymatrix
df.head(5)

index  ...  힘의 역전 - Turn the Power Around
0      0  ...                            0.0
1      1  ...                            0.0
2      2  ...                            0.0
3      3  ...                            0.0
4      4  ...                            0.0

[5 rows x 19524 columns]

In [33]:
def cosine_similarity(data_name):    
    from sklearn.metrics.pairwise import cosine_distances
    similarity = 1 - cosine_distances(data_name)    # sklearn은 정의와 반대이므로 1에서 빼준다.
    return similarity

cos_sim = cosine_similarity(df)    # data set으로 df를 넣음
print(cos_sim.shape)
cos_sim

(350, 350)


array([[1.        , 0.9929966 , 0.99846141, ..., 0.99846137, 0.99846312,
        0.99846361],
       [0.9929966 , 1.        , 0.99453434, ..., 0.99453368, 0.99452982,
        0.99452716],
       [0.99846141, 0.99453434, 1.        , ..., 0.99999571, 0.99999725,
        0.99999761],
       ...,
       [0.99846137, 0.99453368, 0.99999571, ..., 1.        , 0.99999942,
        0.99999863],
       [0.99846312, 0.99452982, 0.99999725, ..., 0.99999942, 1.        ,
        0.99999982],
       [0.99846361, 0.99452716, 0.99999761, ..., 0.99999863, 0.99999982,
        1.        ]])

In [38]:
class Basic(object):
    
    def __init__(self, user_name, neigh_num):
        self.user_name = user_name
        self.neigh_num = neigh_num
    
    """유저의 이름이 들어오면 유저 번호로 변환"""
    def convert_user_num(self):
        
        user_name_list = list(df['user'].unique())
        
        for num in range(len(user_name_list)):
            if user_name_list[num] == self.user_name:
                user_num = num
        
        return user_num

    """target 유저와 유사한 유저 K명을 찾고, cosine 유사도를 이용하여 거리를 구한다"""
    def find_near_neighbor(self):
    
        from sklearn.neighbors import NearestNeighbors
        
        user_num = Basic.convert_user_num(self)
            
        KNN = NearestNeighbors(n_neighbors = self.neigh_num, metric = 'cosine')    # n_neighbors에는 본인이 포함되기 때문에 +1을 해준다.
        KNN.fit(df)    # data set은 utility matrix인 df를 사용
        similar_distance, similar_users = KNN.kneighbors(df)
    
        similars = {}    #유사한 유저와 거리를 dict형식으로 저장
    
        # 유사한 유저
        similar_users = similar_users[user_num][1:]
        similars['sim_users'] = list(similar_users)
    
        # 유사한 유저들과의 거리
        similar_distance = similar_distance[user_num][1:]
        similars['sim_distance'] = similar_distance
    
        return similars
    
    
    """target유저 + 유사한 유저 K명으로 이루어진 새로운 data frame 형성하고, narray 형식으로 반환"""
    def near_neighbors_narray(self):
    
        similars = Basic.find_near_neighbor(self)
        similiar_users_list = similars['sim_users']
        similiar_distances = similars['sim_distance']

        columns = list(df.columns)
        new_df = pd.DataFrame(columns = columns)
    
        for i in range(len(similiar_users_list)):
        
            def concat_row(i):
                neighbor_df = df[df['index'] == similiar_users_list[i]]
                return neighbor_df
        
            neighbor_df = pd.concat([new_df, concat_row(i)])
            new_df = neighbor_df
            
        narray = new_df.values
        narray = narray[:, 2:]
        
        return narray

In [39]:
user_510 = Basic(510, 10)
print(user_510.convert_user_num())
print(user_510.find_near_neighbor())
print(user_510.near_neighbors_narray())

0
{'sim_users': [30, 17, 41, 12, 26, 205, 109, 35, 65], 'sim_distance': array([0.00153422, 0.00153499, 0.00153501, 0.00153542, 0.0015356 ,
       0.00153565, 0.00153572, 0.00153577, 0.00153577])}
[[0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 ...
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]]


In [40]:
class Calculation_rating(Basic):
    
    def __init__(self, user_name, neigh_num):
        Basic.__init__(self, user_name, neigh_num)
        
    """가중평균 값으로 아이템에 대한 target 유저의 평점을 예측"""
    def predict_rating(self):
        
        narray = Basic.near_neighbors_narray(self)    #narray 받음
        similars = Basic.find_near_neighbor(self)
        
        similiar_distances = similars['sim_distance']
    
        rating_list = []    # 가중평균값을 담는 리스트
    
        # 범위 0 ~ K-1
        for col_num in range(narray.shape[1]):
        
            sum = 0
            sum_distance = 0
            rating = 0
            for i in range(1, len(narray[:, col_num])):
                 if float(narray[:, col_num][i]) > 0:
                     sum += float(narray[:, col_num][i]) * float(similiar_distances[i])
                     sum_distance += float(similiar_distances[i])
            if sum_distance != 0: rating = sum/sum_distance
            else: rating = 0
        
            if rating < 0:
                rating = 0    # 만약 가중평균값이 0보다 작으면 0점으로 함
            elif rating > 10:
                rating = 10    # 만약 가중평균값이 10보다 크면 10점으로 함
            #else:
            #   rating = rating    # 평점은 정수형
    
            rating_list.append(rating)

        return rating_list
        
    
    """target 유저의 평점을 리스트로 변환하는 함수"""
    def original_rating(self):
        
        user_num = Basic.convert_user_num(self)
    
        # target 유저의 평점을 narray로 변환
        target_df = df[df['index'] == user_num]
        target_narray = target_df.values
        target_narray = target_narray[:, 2:]    # user column 삭제
    
        #narray로 변환된 target 유저의 평점을 리스트로 변환
        target_user_rating_list = []
        for i in range(target_narray.shape[1]):
            raw_rating = int(target_narray[0][i])
            target_user_rating_list.append(raw_rating)
    
        return target_user_rating_list

In [41]:
user_510 = Calculation_rating(510, 50)
print(sum(user_510.predict_rating()))
print(user_510.original_rating())
print(user_510.predict_rating())

11487.828571622038
[0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [42]:
class UBCF(Calculation_rating):
    
    def __init__ (self, user_name, neigh_num):
        Basic.__init__(self, user_name, neigh_num)
        Calculation_rating.__init__(self, user_name, neigh_num)        
        
    def recommen_book_list(self):
        
        user_num = Basic.convert_user_num(self)
        predict_list = Calculation_rating.predict_rating(self)
        original_list = Calculation_rating.original_rating(self)
        all_book_list = list(df.columns)[3:]    # 전체 도서 리스트
        
        """
        target 유저가 이미 평가했던 도서 외의 도서를 추천받기 위해
        target 유저의 평점이 0이면 가중평균값을 넣고, 그렇지 않으면(이미 평가한 도서면) -1을 넣는다
        """
        temp_list = []
        for i in range(len(predict_list)):
            if original_list[i] != 0:
                temp_list.append(-1)
            else:
                temp_list.append(predict_list[i])

        # 4.5점 이상인 도서들만 선택하여 index를 추천 리스트에 담는다.
        #recommen_list_index =[]
        #for i in range(len(temp_list)):
        #    if temp_list[i] >= 4.5:
        #        recommen_list_index.append(i)

        #예상 평점 기준으로 내림차순 정렬해서 가장 높은 30권의 인덱스를 추출한다.  
        recommen_list = {}
        for i in range(len(temp_list)):
            recommen_list[i] = temp_list[i]
        recommen_list = sorted(recommen_list.items(), key=(lambda x:x[1]), reverse=True)
        recommen_list_index = []
        for i in range(len(recommen_list)):
            recommen_list_index.append(recommen_list[i][0])
        final_recommen_list = recommen_list_index[:10] #몇 권 추천?
        #print(final_recommen_list)
        #print(recommen_list)

        # final_recommen_index로부터 도서 제목을 str로 저장
        recommen_list_str = []
        for i in final_recommen_list:
            recommen_list_str.append(all_book_list[i])
        
        """전체 도서 리스트에서 target 유저가 이미 평가한 영화를 제거"""
        already_rating_book_num = [i for i in range(len(temp_list)) if temp_list[i] == -1]
        user_book_list = [all_book_list[i] for i in range(len(all_book_list)) if i in already_rating_book_num]

        
        final_dict = {}
        final_dict['by_rating'] = recommen_list_str
        final_dict['by_delete'] = user_book_list
        
        return final_dict
    
    
    """도서 추천 실행 함수"""
    def recommendation(self):
        
        user_number = Basic.convert_user_num(self)
        book_dict = UBCF.recommen_book_list(self)
        
        by_rating_list = book_dict['by_rating']
        by_delete_list = book_dict['by_delete']
        #print(by_rating_list)
        #print(len(by_rating_list))
        #print(by_delete_list)
        #print(len(by_delete_list))
        
        ### (x)만약 추천 리스트가 10개 이상이라면 가중평균 리스트에서 10편의 도서를 추천 리스트에서 추천
        ### (x)그렇지 않으면 유저가 이미 평가했던 도서를 제외한 도서 리스트에서 추천
        # 예상 평점 상위 10권의 도서 중 3개를 랜덤으로 선택해서 추천
        if len(by_rating_list) >= 10:
            recommendation_selection = random.sample(by_rating_list, 3)
        else:
            if len(by_delete_list) >= 10 :
                recommendation_selection = random.sample(by_delete_list, 10)
            else:
                recommendation_selection = random.sample(by_delete_list, 1)
            
        user_name = df['user'][user_number]    # user number를 user의 아이디로 변경
    
        #print('{}님을 위한 추천 도서 입니다.'.format(user_name))
        return recommendation_selection

In [44]:
recommendation_510 = UBCF(510, 5)
recommendation_510.recommendation()

['서점 여행자의 노트 - 뉴욕, 런던, 파리의 책방에서 독자로 성장하기',
 '빌 게이츠@생각의 속도 - 디지털 신경망 비즈니스',
 '가재걸음 - 세계는 왜 뒷걸음질 치는가']

In [ ]:
test_user = [182571, 500226, 298590, 403593, 478599, 26322, 190131,214944,237165,540645,580848,30426,348351,580875,48624
,126924
,233655
,413718
,826791
,530385
,523338
,26916
,151332
,211029
,700269
,56832
,686715
,300912
,584628
,248424
,435264
,193155
,357126
,513969
,399300
,187242
,420009
,478518
,592647
,237678
,62205
,133269
,445902
,91311
,307527
,537027
,134241
,497202
,198015
,417579]

test_result = {}
for i in test_user:
    test_result[i] = UBCF(i, 5).recommendation()
print(test_result)


{182571: ['0.1밀리미터의 혁신 - 5년 안에 50배 성장한 발뮤다 디자인의 비밀', '#i세대 - 스마트폰을 손에 쥐고 자란 요즘 세대 이야기', '0 영 ZERO 零 - 김사과 소설'], 500226: ['아가미', '노인과 바다', '죽은 시인의 사회'], 298590: ['지적 대화를 위한 넓고 얕은 지식 : 제로 편', '사랑하라, 두려움 없이 - 톨텍 인디언이 들려주는 사랑의 가르침', '아주 작은 습관의 힘 - 최고의 변화는 어떻게 만들어지는가'], 403593: ['개구리', '개인주의자 선언 - 판사 문유석의 일상유감', '강영안 교수의 십계명 강의 (양장) - 십계명이 열어 보인 삶의 길, 자유의 길'], 478599: ['나는 간호사, 사람입니다 - 단 한 번의 실수도 허락하지 않는 삶을 사는 사람들의 이야기', '#i세대 - 스마트폰을 손에 쥐고 자란 요즘 세대 이야기', '브링 미 백'], 26322: ['뼛속까지 내려가서 써라 - 전 세계 독자들을 사로잡은 혁명적인 글쓰기 방법론', '사피엔스 - 유인원에서 사이보그까지, 인간 역사의 대담하고 위대한 질문', '데미안'], 190131: ['익명의 전화', '죽여 마땅한 사람들', '게임의 이름은 유괴'], 214944: ['롤리타 (무선)', '82년생 김지영 (코멘터리 에디션)', '초판본 노인과 바다 (양장) - 1952년 오리지널 초판본 표지디자인'], 237165: ['당신의 이름을 지어다가 며칠은 먹었다', '맹자', '바깥은 여름'], 540645: ['실행이 답이다 (리커버 에디션) - 행동과 실천의 심리학', '부의 추월차선 - 부자들이 말해 주지 않는 진정한 부를 얻는 방법', '프로덕트 오너 - 조직을 성공으로 이끄는, 쿠팡의 PO가 말하는 애자일 혁신 전략'], 580848: ['바깥은 여름', 'The Present (Paperback)', '노인과 바다'], 30426: ['방구석 미술관 (아티스트 하우스 에디션)', '어느 날, 우리는', '좋은 아침